//LOGIN
const ADD_LOGIN = "ADD_LOGIN";
const LOGIN_LOADING = "LOGIN_LOADING";
const LOGIN_FAILED = "LOGIN_FAILED";
const REMOVE_LOGIN = "REMOVE_LOGIN";
const REMOVE_USER_PASTE = "REMOVE_USER_PASTE";
const ADD_USER_PASTE = "ADD_USER_PASTE";
const SET_USER = "SET_USER"

// Pastes
const SET_PASTES = "SET_PASTES";
const UNSET_PASTES = "UNSET_PASTES";
const ADD_PASTE = "ADD_PASTE";
const UPDATE_PASTE = "UPDATE_PASTE";
const REMOVE_PASTE = "REMOVE_PASTE";
const RENEW_ACCESS_TOKEN = "RENEW_ACCESS_TOKEN";
const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
const SET_BALANCE = "SET_BALANCE";

// Payment
const SET_PAYMENT_DATA = "SET_PAYMENT";
const UNSET_PAYMENT_DATA = "UNSET_PAYMENT";
const SET_PROFILE_DATA = "SET_PROFILE_DATA";
const UNSET_PROFILE_DATA = "UNSET_PROFILE_DATA";
const CLEAR_PAYMENT_DATA = "CLEAR_PAYMENT_DATA";

// current paste actions
const SET_CURRENT_PASTE = "SET_CURRENT_PASTE";
const SET_PASTE_MASTERKEY = "SET_PASTE_MASTERKEY";
const CLEAR_CURRENT_PASTE = "CLEAR_CURRENT_PASTE";
const UPDATE_CURRENT_PASTE = "UPDATE_CURRENT_PASTE";
const SET_CURRENT_PASTE_DATA = "SET_CURRENT_PASTE_DATA";
const SET_CURRENT_PASTE_TITLE = "SET_CURRENT_PASTE_TITLE";
const SET_CURRENT_PASTE_PASSWORD = "SET_CURRENT_PASTE_PASSWORD";
const SET_CURRENT_PASTE_MASTERKEY = "SET_CURRENT_PASTE_MASTERKEY";
const SET_CURRENT_PASTE_MAXVIEWS = "SET_CURRENT_PASTE_MAXVIEWS";
const SET_CURRENT_PASTE_PRIVACY = "SET_CURRENT_PASTE_PRIVACY";
const SET_CURRENT_PASTE_EXPIRY = "SET_CURRENT_PASTE_EXPIRY";
const SET_CURRENT_PASTE_ESEED = "SET_CURRENT_PASTE_ESEED";
const SET_CURRENT_PASTE_VSEED = "SET_CURRENT_PASTE_VSEED";
const SET_CURRENT_PASTE_VCT = "SET_CURRENT_PASTE_VCT";
const SET_CURRENT_PASTE_ECT = "SET_CURRENT_PASTE_ECT";

const SET_CURRENT_FORM_MODE = "SET_CURRENT_FORM_MODE";
const SET_CURRENT_TAG = "SET_CURRENT_TAG";
const SET_PASTE_KEY = "SET_PASTE_KEY";
const SET_PASTE = "SET_PASTE";

const SET_TAB = "SET_TAB";
const REMOVE_TAB = "REMOVE_TAB";
const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
const UPDATE_TAB = "UPDATE_TAB";

const ActionTypes = {
	ADD_LOGIN,
    SET_USER,
	LOGIN_LOADING,
	LOGIN_FAILED,
	REMOVE_LOGIN,
	REMOVE_USER_PASTE,
	ADD_USER_PASTE,

	// single paste manage
	SET_PASTE,
	REMOVE_PASTE,

	// single tab manage
	SET_TAB,
	UPDATE_TAB,
	REMOVE_TAB,
	SET_ACTIVE_TAB,

    ADD_PASTE,
	SET_PASTES,
	UNSET_PASTES,
	UPDATE_PASTE,
	RENEW_ACCESS_TOKEN,
	SET_ACCESS_TOKEN,
	SET_BALANCE,

	SET_PAYMENT_DATA,
	UNSET_PAYMENT_DATA,
	SET_PROFILE_DATA,
	UNSET_PROFILE_DATA,
	CLEAR_PAYMENT_DATA,

	SET_CURRENT_PASTE,
	SET_PASTE_MASTERKEY,
	CLEAR_CURRENT_PASTE,
	UPDATE_CURRENT_PASTE,

	SET_CURRENT_TAG,
	SET_CURRENT_PASTE_DATA,
	SET_CURRENT_PASTE_TITLE,
	SET_CURRENT_PASTE_PASSWORD,
	SET_CURRENT_PASTE_MASTERKEY,
	SET_CURRENT_PASTE_MAXVIEWS,
	SET_CURRENT_PASTE_PRIVACY,
	SET_CURRENT_PASTE_EXPIRY,
	SET_CURRENT_PASTE_ESEED,
    SET_CURRENT_PASTE_VSEED,
    SET_CURRENT_PASTE_VCT,
    SET_CURRENT_PASTE_ECT,
	SET_CURRENT_FORM_MODE,
	SET_PASTE_KEY,
};

export default ActionTypes;
